import React from "react";

import testImage1 from "../assets/images/testImage1.jpg";
import testImage2 from "../assets/images/testImage2.jpg";
import testImage3 from "../assets/images/testImage3.jpg";

const Introduction = ({ onNext }) => {
  const sampleImages = [testImage1, testImage2, testImage3];

  return (
    <div className="text-center bg-white shadow-lg p-6 max-w-4xl rounded-2xl mx-auto">
      <h2 className="text-4xl text-gray-700 font-bold font-sans mt-2 mb-4">
        Welcome to Professional AI Headshot Generator
      </h2>
      <div className="w-full flex justify-center items-center">
        <p className="text-gray-500 mb-10 font-medium font-sans text-sm w-[80%] text-center leading-5">
          Experience the future of professional headshots with our cutting-edge
          AI technology. Our platform is designed to generate high-quality
          headshots that meet the standards of corporate, casual, and formal
          settings. Below are some examples of headshots generated by our AI.
        </p>
      </div>

      <div className="flex justify-center space-x-4 mb-6">
        {sampleImages.map((src, index) => (
          <img
            key={index}
            src={src}
            alt={`Sample ${index}`}
            className="w-[32%] h-96 rounded-3xl shadow-md"
          />
        ))}
      </div>
      <button
        onClick={onNext}
        className="bg-purple-500 hover:bg-purple-600 text-white w-full py-2 px-4 font-sans font-bold rounded-2xl hover:to-purple-700 transition mt-2 mb-2"
      >
        Get Started
      </button>
    </div>
  );
};

export default Introduction;
